
spring:
  application:
    name: Auth-Sim
  datasource:
    username: root
    password: ""
    url: jdbc:mysql://localhost:3306/authsim?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  data:
    redis:
      host: 43.163.218.127
      port: 6379
      password: ""


#整合mybatis
mybatis:
  type-aliases-package: cia.northboat.authsim.dto
  # classpath 指 resources 目录
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8080
